// 西语每日练 · 离线词典数据（内容版）
// 铁律：已发布词条的 w 永不改名；释义课程语境优先，每条 1-3 个义项。
// conj 字段 = 指向 VERBS_DATA 里的动词原形（自动展示变位表）。
// DICT_FORMS_DATA = 变形 → 原形（20 个核心动词的变形由 index.html 从 VERBS_DATA
// 自动生成，这里只补其他动词和分词/副动词等）。
var DICT_DATA = [
    { w: "a", pos: "prep.", zh: ["到，向；在（时间点）"] },
    { w: "abierto, abierta", pos: "adj.", zh: ["开着的"] },
    { w: "abril", pos: "m.", zh: ["四月"] },
    { w: "abrir", pos: "v.", zh: ["打开"], conj: "abrir" },
    { w: "abuela", pos: "f.", zh: ["奶奶，外婆"] },
    { w: "abuelo, abuela", pos: "m./f.", zh: ["爷爷，外公 / 奶奶，外婆"] },
    { w: "aburrido, aburrida", pos: "adj.", zh: ["无聊的，枯燥的"] },
    { w: "acostarse", pos: "v.", zh: ["上床睡觉"] },
    { w: "agradecer", pos: "v.", zh: ["感谢"] },
    { w: "agua", pos: "f.", zh: ["水"] },
    { w: "ahora", pos: "adv.", zh: ["现在"] },
    { w: "al", pos: "prep.", zh: ["（a + el 的缩合）到…（阳性单数名词前）"] },
    { w: "alcohol", pos: "m.", zh: ["酒精，酒"] },
    { w: "alegrarse", pos: "v.", zh: ["感到高兴"] },
    { w: "alegre", pos: "adj.", zh: ["快乐的，高兴的"] },
    { w: "algo", pos: "pron.", zh: ["某事物，一些东西"] },
    { w: "allí", pos: "adv.", zh: ["那里"] },
    { w: "almuerzo", pos: "m.", zh: ["午餐"] },
    { w: "alto, alta", pos: "adj.", zh: ["高的；大声的"] },
    { w: "amable", pos: "adj.", zh: ["和蔼的，友善的"] },
    { w: "amiga", pos: "f.", zh: ["女性朋友"] },
    { w: "amigo, amiga", pos: "m./f.", zh: ["朋友"] },
    { w: "Ana", pos: "人名", zh: ["安娜"] },
    { w: "anoche", pos: "adv.", zh: ["昨晚"] },
    { w: "antiguo, antigua", pos: "adj.", zh: ["古老的，旧的"] },
    { w: "año", pos: "m.", zh: ["年；岁"] },
    { w: "aeropuerto", pos: "m.", zh: ["机场"] },
    { w: "antes", pos: "adv.", zh: ["之前（antes de … 在…之前）"] },
    { w: "aprender", pos: "v.", zh: ["学习，学会"], conj: "aprender" },
    { w: "aquel, aquella", pos: "pron.", zh: ["那个（离双方都远）"] },
    { w: "aquí", pos: "adv.", zh: ["这里"] },
    { w: "autobús", pos: "m.", zh: ["公交车"] },
    { w: "avión", pos: "m.", zh: ["飞机"] },
    { w: "ayer", pos: "adv.", zh: ["昨天"] },
    { w: "ayuda", pos: "f.", zh: ["帮助"] },
    { w: "ayudar", pos: "v.", zh: ["帮助"] },
    { w: "azúcar", pos: "m.", zh: ["糖"] },
    { w: "bailar", pos: "v.", zh: ["跳舞"] },
    { w: "baloncesto", pos: "m.", zh: ["篮球（运动）"] },
    { w: "banco", pos: "m.", zh: ["银行；长椅"] },
    { w: "barato, barata", pos: "adj.", zh: ["便宜的"] },
    { w: "Barcelona", pos: "地名", zh: ["巴塞罗那"] },
    { w: "barrio", pos: "m.", zh: ["街区，社区"] },
    { w: "beber", pos: "v.", zh: ["喝"], conj: "beber" },
    { w: "biblioteca", pos: "f.", zh: ["图书馆"] },
    { w: "bien", pos: "adv.", zh: ["好；很好"] },
    { w: "boda", pos: "f.", zh: ["婚礼"] },
    { w: "bonito, bonita", pos: "adj.", zh: ["漂亮的"] },
    { w: "buen", pos: "adj.", zh: ["好的（bueno 在阳性名词前的短尾形式）"] },
    { w: "bueno, buena", pos: "adj.", zh: ["好的；善良的"] },
    { w: "cabeza", pos: "f.", zh: ["头"] },
    { w: "cada", pos: "adj.", zh: ["每，每个"] },
    { w: "café", pos: "m.", zh: ["咖啡；咖啡馆"] },
    { w: "calle", pos: "f.", zh: ["街道"] },
    { w: "calor", pos: "m.", zh: ["热（hace calor 天气热）"] },
    { w: "cama", pos: "f.", zh: ["床"] },
    { w: "caminar", pos: "v.", zh: ["走路，步行"] },
    { w: "camisa", pos: "f.", zh: ["衬衫"] },
    { w: "campo", pos: "m.", zh: ["乡村，田野"] },
    { w: "cansado, cansada", pos: "adj.", zh: ["累的，疲倦的"] },
    { w: "capítulo", pos: "m.", zh: ["章节"] },
    { w: "cara", pos: "f.", zh: ["脸"] },
    { w: "carne", pos: "f.", zh: ["肉"] },
    { w: "caro, cara", pos: "adj.", zh: ["贵的"] },
    { w: "carta", pos: "f.", zh: ["信，书信"] },
    { w: "casa", pos: "f.", zh: ["房子；家"] },
    { w: "casco", pos: "m.", zh: ["头盔"] },
    { w: "casi", pos: "adv.", zh: ["几乎，差不多"] },
    { w: "castillo", pos: "m.", zh: ["城堡"] },
    { w: "celebrar", pos: "v.", zh: ["庆祝"] },
    { w: "cena", pos: "f.", zh: ["晚餐"] },
    { w: "cenar", pos: "v.", zh: ["吃晚餐"] },
    { w: "centro", pos: "m.", zh: ["中心"] },
    { w: "cerca", pos: "adv.", zh: ["近（cerca de … 在…附近）"] },
    { w: "cerrado, cerrada", pos: "adj.", zh: ["关着的，关闭的"] },
    { w: "cerrar", pos: "v.", zh: ["关闭"] },
    { w: "chaqueta", pos: "f.", zh: ["夹克，外套"] },
    { w: "chica", pos: "f.", zh: ["女孩"] },
    { w: "chico, chica", pos: "m./f.", zh: ["男孩 / 女孩"] },
    { w: "Chile", pos: "地名", zh: ["智利"] },
    { w: "China", pos: "地名", zh: ["中国"] },
    { w: "chino, china", pos: "adj./m./f.", zh: ["中国的 / 中国人"] },
    { w: "cien", pos: "num.", zh: ["一百"] },
    { w: "cinco", pos: "num.", zh: ["五"] },
    { w: "cincuenta", pos: "num.", zh: ["五十"] },
    { w: "cine", pos: "m.", zh: ["电影院；电影"] },
    { w: "cita", pos: "f.", zh: ["约会；预约"] },
    { w: "ciudad", pos: "f.", zh: ["城市"] },
    { w: "claro", pos: "interj./adj.", zh: ["当然；清楚的"] },
    { w: "clase", pos: "f.", zh: ["课；班级；教室"] },
    { w: "coche", pos: "m.", zh: ["汽车"] },
    { w: "cocinar", pos: "v.", zh: ["做饭"] },
    { w: "color", pos: "m.", zh: ["颜色"] },
    { w: "comer", pos: "v.", zh: ["吃"], conj: "comer" },
    { w: "comida", pos: "f.", zh: ["食物；饭"] },
    { w: "cómodo, cómoda", pos: "adj.", zh: ["舒服的"] },
    { w: "compañero, compañera", pos: "m./f.", zh: ["同学，同事，同伴"] },
    { w: "comprar", pos: "v.", zh: ["买"], conj: "comprar" },
    { w: "con", pos: "prep.", zh: ["和，跟，用，带着"] },
    { w: "conmigo", pos: "pron.", zh: ["和我（con + mí）"] },
    { w: "conocer", pos: "v.", zh: ["认识；了解"] },
    { w: "contar", pos: "v.", zh: ["讲述；数数"] },
    { w: "contento, contenta", pos: "adj.", zh: ["高兴的，满意的"] },
    { w: "contestar", pos: "v.", zh: ["回答"] },
    { w: "contigo", pos: "pron.", zh: ["和你（con + ti）"] },
    { w: "comenzar", pos: "v.", zh: ["开始"] },
    { w: "acuerdo", pos: "m.", zh: ["同意（de acuerdo 同意，好）"] },
    { w: "divertirse", pos: "v.", zh: ["玩得开心"] },
    { w: "Li", pos: "人名", zh: ["李（姓）"] },
    { w: "Ming", pos: "人名", zh: ["明（名）"] },
    { w: "ninguno, ninguna", pos: "pron.", zh: ["没有一个（no … ninguno 一个也不）"] },
    { w: "correr", pos: "v.", zh: ["跑步"] },
    { w: "costar", pos: "v.", zh: ["值（多少钱）；费力"] },
    { w: "creer", pos: "v.", zh: ["相信；认为"] },
    { w: "cuál, cuáles", pos: "pron.", zh: ["哪一个，哪些"] },
    { w: "cuando, cuándo", pos: "conj./pron.", zh: ["当…时候", "什么时候（cuándo，重音不同）"] },
    { w: "como, cómo", pos: "conj./pron.", zh: ["像，如同", "怎么，怎样（¿cómo? 怎么样？）"] },
    { w: "cuánto, cuánta", pos: "pron.", zh: ["多少"] },
    { w: "cuarenta", pos: "num.", zh: ["四十"] },
    { w: "cumpleaños", pos: "m.", zh: ["生日"] },
    { w: "cumplir", pos: "v.", zh: ["完成；满（…岁）"] },
    { w: "dar", pos: "v.", zh: ["给"], conj: "dar" },
    { w: "de", pos: "prep.", zh: ["的；从；关于"] },
    { w: "deber", pos: "m.", zh: ["义务；作业（deberes 常为复数）"] },
    { w: "decidir", pos: "v.", zh: ["决定"] },
    { w: "decir", pos: "v.", zh: ["说，告诉"], conj: "decir" },
    { w: "del", pos: "prep.", zh: ["（de + el 的缩合）…的（阳性单数名词前）"] },
    { w: "demasiado, demasiada", pos: "adj./adv.", zh: ["太多的；太，过于"] },
    { w: "derecho, derecha", pos: "adj./adv.", zh: ["右的；直走（todo derecho 一直走）"] },
    { w: "desayunar", pos: "v.", zh: ["吃早餐"] },
    { w: "desayuno", pos: "m.", zh: ["早餐"] },
    { w: "descansar", pos: "v.", zh: ["休息"] },
    { w: "desde", pos: "prep.", zh: ["从…起，自"] },
    { w: "despacio", pos: "adv.", zh: ["慢慢地"] },
    { w: "despedirse", pos: "v.", zh: ["告别，告辞"] },
    { w: "devolver", pos: "v.", zh: ["归还，退回"] },
    { w: "día", pos: "m.", zh: ["天，日子；白天"] },
    { w: "diario, diaria", pos: "adj.", zh: ["每天的"] },
    { w: "diccionario", pos: "m.", zh: ["词典"] },
    { w: "diez", pos: "num.", zh: ["十"] },
    { w: "difícil", pos: "adj.", zh: ["困难的"] },
    { w: "dime", pos: "fr.", zh: ["告诉我（decir 命令式 + me）"] },
    { w: "dirección", pos: "f.", zh: ["地址；方向"] },
    { w: "doler", pos: "v.", zh: ["疼，痛（me duele … 我…疼）"] },
    { w: "domingo", pos: "m.", zh: ["星期天"] },
    { w: "dónde", pos: "pron.", zh: ["哪里"] },
    { w: "dormir", pos: "v.", zh: ["睡觉"] },
    { w: "dos", pos: "num.", zh: ["二"] },
    { w: "doscientos, doscientas", pos: "num.", zh: ["二百"] },
    { w: "durante", pos: "prep.", zh: ["在…期间"] },
    { w: "edificio", pos: "m.", zh: ["大楼，建筑物"] },
    { w: "el, la, los, las, él", pos: "art./pron.", zh: ["定冠词：这（那）个，这些", "他（él，重音不同）"] },
    { w: "ella", pos: "pron.", zh: ["她"] },
    { w: "ellos, ellas", pos: "pron.", zh: ["他们，她们"] },
    { w: "empezar", pos: "v.", zh: ["开始"] },
    { w: "empresa", pos: "f.", zh: ["公司"] },
    { w: "en", pos: "prep.", zh: ["在…里；在（地点/时间）"] },
    { w: "encantado, encantada", pos: "adj.", zh: ["很高兴（encantado de conocerte 很高兴认识你）"] },
    { w: "encantar", pos: "v.", zh: ["使非常喜欢（me encanta … 我非常喜欢…）"] },
    { w: "enfrente", pos: "adv.", zh: ["对面（enfrente de … 在…对面）"] },
    { w: "enseñar", pos: "v.", zh: ["教；给…看"] },
    { w: "entender", pos: "v.", zh: ["理解，听懂"] },
    { w: "escribir", pos: "v.", zh: ["写"], conj: "escribir" },
    { w: "escuchar", pos: "v.", zh: ["听"] },
    { w: "escuela", pos: "f.", zh: ["学校"] },
    { w: "ese, esa", pos: "pron.", zh: ["那个"] },
    { w: "España", pos: "地名", zh: ["西班牙"] },
    { w: "español, española", pos: "adj./m./f.", zh: ["西班牙的 / 西班牙人 / 西班牙语"] },
    { w: "esperar", pos: "v.", zh: ["等待；希望"] },
    { w: "esposa", pos: "f.", zh: ["妻子"] },
    { w: "esquina", pos: "f.", zh: ["街角"] },
    { w: "estación", pos: "f.", zh: ["车站；季节"] },
    { w: "estar", pos: "v.", zh: ["在（某处）；处于（某状态）"], conj: "estar" },
    { w: "este, esta", pos: "pron.", zh: ["这个（esta 也可是 estar 的重音变形 → 在）"] },
    { w: "esto", pos: "pron.", zh: ["这个（中性，指代不明确事物）"] },
    { w: "estudiante", pos: "m./f.", zh: ["学生"] },
    { w: "estudiar", pos: "v.", zh: ["学习，研究"], conj: "estudiar" },
    { w: "examen", pos: "m.", zh: ["考试"] },
    { w: "explicar", pos: "v.", zh: ["解释，讲解"] },
    { w: "faltar", pos: "v.", zh: ["缺少（hace falta … 需要…）"] },
    { w: "familia", pos: "f.", zh: ["家庭"] },
    { w: "famoso, famosa", pos: "adj.", zh: ["著名的"] },
    { w: "fantástico, fantástica", pos: "adj.", zh: ["极好的，棒极了的"] },
    { w: "farmacia", pos: "f.", zh: ["药店"] },
    { w: "favor", pos: "m.", zh: ["帮忙（por favor 请）"] },
    { w: "favorito, favorita", pos: "adj.", zh: ["最喜欢的"] },
    { w: "felicidades", pos: "interj.", zh: ["祝贺！恭喜！"] },
    { w: "felicitar", pos: "v.", zh: ["祝贺"] },
    { w: "fiebre", pos: "f.", zh: ["发烧"] },
    { w: "fiesta", pos: "f.", zh: ["聚会，派对；节日"] },
    { w: "fin", pos: "m.", zh: ["结束，结尾（fin de semana 周末）"] },
    { w: "final", pos: "m.", zh: ["结束；决赛"] },
    { w: "flor", pos: "f.", zh: ["花"] },
    { w: "foto", pos: "f.", zh: ["照片"] },
    { w: "fresco, fresca", pos: "adj.", zh: ["新鲜的；凉爽的"] },
    { w: "frío", pos: "m./adj.", zh: ["冷（hace frío 天气冷）/ 冷的"] },
    { w: "fruta", pos: "f.", zh: ["水果"] },
    { w: "fumar", pos: "v.", zh: ["吸烟"] },
    { w: "fútbol", pos: "m.", zh: ["足球"] },
    { w: "gerundio", pos: "m.", zh: ["副动词（-ando / -iendo 形式）"] },
    { w: "gracias", pos: "f./interj.", zh: ["谢谢（gracias a … 多亏…）"] },
    { w: "gracioso, graciosa", pos: "adj.", zh: ["有趣的，好笑的"] },
    { w: "grande", pos: "adj.", zh: ["大的"] },
    { w: "guapo, guapa", pos: "adj.", zh: ["漂亮的，帅的"] },
    { w: "guardar", pos: "v.", zh: ["保存；留着"] },
    { w: "guitarra", pos: "f.", zh: ["吉他"] },
    { w: "gustar", pos: "v.", zh: ["使喜欢（me gusta … 我喜欢…）"] },
    { w: "gusto", pos: "m.", zh: ["口味；高兴（mucho gusto 很高兴认识你）"] },
    { w: "haber", pos: "v.", zh: ["有（hay …）；助动词（he hecho 我做了）"] },
    { w: "hablar", pos: "v.", zh: ["说，讲话"], conj: "hablar" },
    { w: "hacer", pos: "v.", zh: ["做，干；（天气）hace calor/frío"], conj: "hacer" },
    { w: "Halloween", pos: "m.", zh: ["万圣节"] },
    { w: "hasta", pos: "prep.", zh: ["直到"] },
    { w: "hermana", pos: "f.", zh: ["姐妹"] },
    { w: "hermano, hermana", pos: "m./f.", zh: ["兄弟 / 姐妹"] },
    { w: "hija", pos: "f.", zh: ["女儿"] },
    { w: "hijo, hija", pos: "m./f.", zh: ["儿子 / 女儿"] },
    { w: "historia", pos: "f.", zh: ["历史；故事"] },
    { w: "hola", pos: "interj.", zh: ["你好"] },
    { w: "hora", pos: "f.", zh: ["小时；时刻（¿Qué hora es? 几点了？）"] },
    { w: "hospital", pos: "m.", zh: ["医院"] },
    { w: "hotel", pos: "m.", zh: ["酒店"] },
    { w: "hoy", pos: "adv.", zh: ["今天"] },
    { w: "idea", pos: "f.", zh: ["主意，想法"] },
    { w: "idioma", pos: "m.", zh: ["语言"] },
    { w: "iglesia", pos: "f.", zh: ["教堂"] },
    { w: "importante", pos: "adj.", zh: ["重要的"] },
    { w: "ingeniería", pos: "f.", zh: ["工程学"] },
    { w: "interesante", pos: "adj.", zh: ["有趣的"] },
    { w: "internet", pos: "m.", zh: ["互联网"] },
    { w: "invierno", pos: "m.", zh: ["冬天"] },
    { w: "invitar", pos: "v.", zh: ["邀请；请客"] },
    { w: "ir", pos: "v.", zh: ["去（ir a + inf. 打算做…）"], conj: "ir" },
    { w: "jugar", pos: "v.", zh: ["玩；踢（球）"] },
    { w: "jueves", pos: "m.", zh: ["星期四"] },
    { w: "junto, juntos", pos: "adj./adv.", zh: ["一起的；一起（junto a … 在…旁边）"] },
    { w: "lado", pos: "m.", zh: ["边，侧（al lado de … 在…旁边）"] },
    { w: "largo, larga", pos: "adj.", zh: ["长的"] },
    { w: "lavar", pos: "v.", zh: ["洗"] },
    { w: "le, les", pos: "pron.", zh: ["他/她/您（宾格或与格，第三人称间接宾语）"] },
    { w: "leer", pos: "v.", zh: ["阅读"] },
    { w: "lejos", pos: "adv.", zh: ["远（lejos de … 离…远）"] },
    { w: "lento, lenta", pos: "adj.", zh: ["慢的"] },
    { w: "levantarse", pos: "v.", zh: ["起床；站起来"] },
    { w: "Li Ming", pos: "人名", zh: ["李明"] },
    { w: "libro", pos: "m.", zh: ["书"] },
    { w: "llamar", pos: "v.", zh: ["打电话（llamarse 名叫…）"] },
    { w: "llave", pos: "f.", zh: ["钥匙"] },
    { w: "llegar", pos: "v.", zh: ["到达"] },
    { w: "llevar", pos: "v.", zh: ["带着，穿着；花费（时间）"] },
    { w: "llamarse", pos: "v.", zh: ["名叫…（me llamo … 我叫…）"] },
    { w: "llover", pos: "v.", zh: ["下雨"] },
    { w: "lo, la, los, las", pos: "pron.", zh: ["他/她/它/他们（直接宾语代词）"] },
    { w: "luego", pos: "adv.", zh: ["然后，之后"] },
    { w: "lugar", pos: "m.", zh: ["地方"] },
    { w: "lunes", pos: "m.", zh: ["星期一"] },
    { w: "madre", pos: "f.", zh: ["母亲"] },
    { w: "Madrid", pos: "地名", zh: ["马德里"] },
    { w: "madrugar", pos: "v.", zh: ["早起"] },
    { w: "mal", pos: "adv.", zh: ["坏，不好（mal tiempo 坏天气）"] },
    { w: "mañana", pos: "f./adv.", zh: ["早晨；明天"] },
    { w: "mandar", pos: "v.", zh: ["命令；寄"] },
    { w: "mar", pos: "m./f.", zh: ["大海"] },
    { w: "María", pos: "人名", zh: ["玛丽亚"] },
    { w: "marisco", pos: "m.", zh: ["海鲜"] },
    { w: "martes", pos: "m.", zh: ["星期二"] },
    { w: "más", pos: "adv.", zh: ["更，更多（más … que 比…更）"] },
    { w: "mayor", pos: "adj.", zh: ["更大的；年长的"] },
    { w: "me", pos: "pron.", zh: ["我（宾格/与格代词）"] },
    { w: "media", pos: "f.", zh: ["半小时（y media …点半）"] },
    { w: "medicina", pos: "f.", zh: ["药；医学"] },
    { w: "médico, médica", pos: "m./f.", zh: ["医生"] },
    { w: "mediodía", pos: "m.", zh: ["中午"] },
    { w: "mejor", pos: "adj./adv.", zh: ["更好的，更好（mejor que … 比…好）"] },
    { w: "menos", pos: "adv.", zh: ["更少（menos … que 比…少）"] },
    { w: "mensaje", pos: "m.", zh: ["消息，短信"] },
    { w: "menudo, menuda", pos: "adj.", zh: ["小的（a menudo 经常）"] },
    { w: "mercado", pos: "m.", zh: ["市场"] },
    { w: "mes", pos: "m.", zh: ["月份"] },
    { w: "mesa", pos: "f.", zh: ["桌子"] },
    { w: "metro", pos: "m.", zh: ["地铁；米"] },
    { w: "mexicano, mexicana", pos: "adj.", zh: ["墨西哥的 / 墨西哥人"] },
    { w: "México", pos: "地名", zh: ["墨西哥"] },
    { w: "mi, mis, mí", pos: "adj./pron.", zh: ["我的", "我（介词后用 mí，para mí 对我来说）"] },
    { w: "miércoles", pos: "m.", zh: ["星期三"] },
    { w: "mil", pos: "num.", zh: ["一千"] },
    { w: "mío, mía", pos: "pron.", zh: ["我的（el libro es mío 这书是我的）"] },
    { w: "mirar", pos: "v.", zh: ["看"] },
    { w: "mismo, misma", pos: "adj.", zh: ["相同的；本身"] },
    { w: "mochila", pos: "f.", zh: ["背包"] },
    { w: "momento", pos: "m.", zh: ["时刻，片刻（en este momento 此刻）"] },
    { w: "montaña", pos: "f.", zh: ["山"] },
    { w: "mucho, mucha", pos: "adj./adv.", zh: ["很多的；非常"] },
    { w: "mudanza", pos: "f.", zh: ["搬家"] },
    { w: "mudarse", pos: "v.", zh: ["搬家"] },
    { w: "museo", pos: "m.", zh: ["博物馆"] },
    { w: "música", pos: "f.", zh: ["音乐"] },
    { w: "muy", pos: "adv.", zh: ["非常，很"] },
    { w: "nada", pos: "pron.", zh: ["没有什么（no … nada 什么都不）"] },
    { w: "nadie", pos: "pron.", zh: ["没有人（no … nadie 谁也不）"] },
    { w: "Navidad", pos: "f.", zh: ["圣诞节"] },
    { w: "necesitar", pos: "v.", zh: ["需要"] },
    { w: "nevar", pos: "v.", zh: ["下雪"] },
    { w: "ni", pos: "conj.", zh: ["也不（no … ni … 既不…也不…）"] },
    { w: "niño, niña", pos: "m./f.", zh: ["孩子，小孩"] },
    { w: "no", pos: "adv.", zh: ["不；没有"] },
    { w: "noche", pos: "f.", zh: ["晚上（por la noche 在晚上）"] },
    { w: "nombre", pos: "m.", zh: ["名字"] },
    { w: "nos", pos: "pron.", zh: ["我们（宾格/与格代词）"] },
    { w: "nosotros, nosotras", pos: "pron.", zh: ["我们"] },
    { w: "noticia", pos: "f.", zh: ["新闻，消息"] },
    { w: "nuestro, nuestra", pos: "adj./pron.", zh: ["我们的"] },
    { w: "nueve", pos: "num.", zh: ["九"] },
    { w: "nuevo, nueva", pos: "adj.", zh: ["新的"] },
    { w: "número", pos: "m.", zh: ["数字，号码"] },
    { w: "obra", pos: "f.", zh: ["作品；工程"] },
    { w: "ochenta", pos: "num.", zh: ["八十"] },
    { w: "ocho", pos: "num.", zh: ["八"] },
    { w: "ocupado, ocupada", pos: "adj.", zh: ["忙的；被占用的"] },
    { w: "oficina", pos: "f.", zh: ["办公室"] },
    { w: "oír", pos: "v.", zh: ["听见"] },
    { w: "ojalá", pos: "interj.", zh: ["但愿（后接虚拟式：ojalá + subj. 希望…）"] },
    { w: "once", pos: "num.", zh: ["十一"] },
    { w: "opinión", pos: "f.", zh: ["意见，看法"] },
    { w: "organizar", pos: "v.", zh: ["组织"] },
    { w: "orilla", pos: "f.", zh: ["河岸，岸边"] },
    { w: "otro, otra", pos: "adj./pron.", zh: ["另一个（otra vez 再一次）"] },
    { w: "paciente", pos: "m./f./adj.", zh: ["病人 / 有耐心的"] },
    { w: "padre", pos: "m.", zh: ["父亲"] },
    { w: "padres", pos: "m.pl.", zh: ["父母"] },
    { w: "paella", pos: "f.", zh: ["海鲜饭（西班牙特色菜）"] },
    { w: "país", pos: "m.", zh: ["国家"] },
    { w: "palabra", pos: "f.", zh: ["词，单词"] },
    { w: "pan", pos: "m.", zh: ["面包"] },
    { w: "panadería", pos: "f.", zh: ["面包店"] },
    { w: "para", pos: "prep.", zh: ["为了；给；到（para + inf. 为了做…）"] },
    { w: "parecer", pos: "v.", zh: ["好像，看起来"] },
    { w: "parque", pos: "m.", zh: ["公园"] },
    { w: "parte", pos: "f.", zh: ["部分"] },
    { w: "pasado, pasada", pos: "adj./m.", zh: ["过去的 / 过去（时间）"] },
    { w: "pasar", pos: "v.", zh: ["经过；度过；发生"] },
    { w: "pasear", pos: "v.", zh: ["散步"] },
    { w: "pasta", pos: "f.", zh: ["面食，意面"] },
    { w: "pedir", pos: "v.", zh: ["请求；点（菜）"] },
    { w: "Pekín", pos: "地名", zh: ["北京"] },
    { w: "película", pos: "f.", zh: ["电影"] },
    { w: "pena", pos: "f.", zh: ["遗憾（es una pena 真可惜）"] },
    { w: "peor", pos: "adj./adv.", zh: ["更差的，更糟"] },
    { w: "pequeño, pequeña", pos: "adj.", zh: ["小的"] },
    { w: "perder", pos: "v.", zh: ["失去；输掉；错过"] },
    { w: "perdón", pos: "interj.", zh: ["对不起，请原谅"] },
    { w: "periódico", pos: "m.", zh: ["报纸"] },
    { w: "pero", pos: "conj.", zh: ["但是"] },
    { w: "persona", pos: "f.", zh: ["人"] },
    { w: "Perú", pos: "地名", zh: ["秘鲁"] },
    { w: "pescado", pos: "m.", zh: ["鱼（食物）"] },
    { w: "plan", pos: "m.", zh: ["计划"] },
    { w: "playa", pos: "f.", zh: ["海滩"] },
    { w: "plaza", pos: "f.", zh: ["广场"] },
    { w: "poco, poca", pos: "adj./adv.", zh: ["少的；一点儿（un poco 一点儿）"] },
    { w: "poder", pos: "v.", zh: ["能，可以（poder + inf.）"], conj: "poder" },
    { w: "policía", pos: "m./f.", zh: ["警察"] },
    { w: "pollo", pos: "m.", zh: ["鸡肉；鸡"] },
    { w: "poner", pos: "v.", zh: ["放，放置"] },
    { w: "por", pos: "prep.", zh: ["因为；为了；通过；每（por la mañana 在上午）"] },
    { w: "porque", pos: "conj.", zh: ["因为"] },
    { w: "postal", pos: "f.", zh: ["明信片"] },
    { w: "practicar", pos: "v.", zh: ["练习"] },
    { w: "pregunta", pos: "f.", zh: ["问题"] },
    { w: "preguntar", pos: "v.", zh: ["问，询问"] },
    { w: "preocuparse", pos: "v.", zh: ["担心（no te preocupes 别担心）"] },
    { w: "preparar", pos: "v.", zh: ["准备"] },
    { w: "primavera", pos: "f.", zh: ["春天"] },
    { w: "primaria", pos: "f.", zh: ["（escuela primaria）小学"] },
    { w: "primero, primera", pos: "adj./adv.", zh: ["第一的；首先"] },
    { w: "primo, prima", pos: "m./f.", zh: ["堂/表兄弟姐妹"] },
    { w: "profesor, profesora", pos: "m./f.", zh: ["老师"] },
    { w: "puerta", pos: "f.", zh: ["门"] },
    { w: "que, qué", pos: "conj./pron.", zh: ["（关系词/连词）…的；比（más … que）", "什么（¿qué? 什么？¡qué + adj.! 多么…！）"] },
    { w: "quedar", pos: "v.", zh: ["剩下；约定（quedarse 留下，待在）"] },
    { w: "quedarse", pos: "v.", zh: ["留下，待在（me quedo en casa 我待在家）"] },
    { w: "querer", pos: "v.", zh: ["想要；爱"], conj: "querer" },
    { w: "queso", pos: "m.", zh: ["奶酪"] },
    { w: "quién, quiénes", pos: "pron.", zh: ["谁"] },
    { w: "quisiera", pos: "v.", zh: ["我想要（querer 的委婉过去式，点餐常用）"] },
    { w: "ramo", pos: "m.", zh: ["花束"] },
    { w: "rápido, rápida", pos: "adj./adv.", zh: ["快的；快速地"] },
    { w: "razón", pos: "f.", zh: ["道理，理由（tener razón 说得对）"] },
    { w: "recibir", pos: "v.", zh: ["收到；接待"] },
    { w: "recomendar", pos: "v.", zh: ["推荐"] },
    { w: "regalo", pos: "m.", zh: ["礼物"] },
    { w: "repetir", pos: "v.", zh: ["重复"] },
    { w: "reseña", pos: "f.", zh: ["评论，评价"] },
    { w: "respuesta", pos: "f.", zh: ["回答，答案"] },
    { w: "restaurante", pos: "m.", zh: ["餐馆"] },
    { w: "reunión", pos: "f.", zh: ["会议"] },
    { w: "río", pos: "m.", zh: ["河流"] },
    { w: "rojo, roja", pos: "adj.", zh: ["红色的"] },
    { w: "ropa", pos: "f.", zh: ["衣服"] },
    { w: "ruidoso, ruidosa", pos: "adj.", zh: ["吵闹的"] },
    { w: "rutina", pos: "f.", zh: ["日常习惯，规律"] },
    { w: "sábado", pos: "m.", zh: ["星期六"] },
    { w: "saber", pos: "v.", zh: ["知道；会（做某事）"] },
    { w: "salir", pos: "v.", zh: ["出去，离开"] },
    { w: "sano, sana", pos: "adj.", zh: ["健康的"] },
    { w: "se", pos: "pron.", zh: ["（反身代词）自己；（无人称）人们（se habla 人们说）"] },
    { w: "seguir", pos: "v.", zh: ["继续；跟随"] },
    { w: "seis", pos: "num.", zh: ["六"] },
    { w: "semana", pos: "f.", zh: ["星期（la semana que viene 下周）"] },
    { w: "sentar", pos: "v.", zh: ["使坐下（sentarse 坐下）"] },
    { w: "sentir", pos: "v.", zh: ["感觉（sentirse 觉得）"] },
    { w: "señora", pos: "f.", zh: ["女士，夫人"] },
    { w: "septiembre", pos: "m.", zh: ["九月"] },
    { w: "ser", pos: "v.", zh: ["是（本质、身份）"], conj: "ser" },
    { w: "servir", pos: "v.", zh: ["服务；上（菜）"] },
    { w: "setenta", pos: "num.", zh: ["七十"] },
    { w: "Shanghai", pos: "地名", zh: ["上海"] },
    { w: "si, sí", pos: "conj./adv.", zh: ["如果", "是，对（sí，表示肯定，重音不同）"] },
    { w: "siempre", pos: "adv.", zh: ["总是"] },
    { w: "siete", pos: "num.", zh: ["七"] },
    { w: "silencio", pos: "m.", zh: ["安静，沉默"] },
    { w: "simpático, simpática", pos: "adj.", zh: ["可爱的，讨人喜欢的"] },
    { w: "simple", pos: "adj.", zh: ["简单的"] },
    { w: "sin", pos: "prep.", zh: ["没有，无"] },
    { w: "sobre", pos: "prep.", zh: ["关于；在…上面"] },
    { w: "sol", pos: "m.", zh: ["太阳"] },
    { w: "solo, sola", pos: "adj./adv.", zh: ["独自的；只有，仅仅"] },
    { w: "sopa", pos: "f.", zh: ["汤"] },
    { w: "sorprender", pos: "v.", zh: ["使惊讶"] },
    { w: "su, sus", pos: "adj.", zh: ["他/她/您/他们的"] },
    { w: "sueño", pos: "m.", zh: ["睡眠；梦（tener sueño 困了）"] },
    { w: "suerte", pos: "f.", zh: ["运气（buena suerte 祝好运）"] },
    { w: "sur", pos: "m.", zh: ["南方"] },
    { w: "Susana", pos: "人名", zh: ["苏珊娜"] },
    { w: "suyo, suya", pos: "pron.", zh: ["他/她/您/他们的（物主代词）"] },
    { w: "talla", pos: "f.", zh: ["（衣服）尺码"] },
    { w: "tan", pos: "adv.", zh: ["如此，那么（tan … como 和…一样）"] },
    { w: "tanto, tanta", pos: "adj./adv.", zh: ["那么多的（tanto … como 和…一样多）"] },
    { w: "tapas", pos: "f.pl.", zh: ["西班牙小吃拼盘"] },
    { w: "tarde", pos: "f./adv.", zh: ["下午；晚，迟"] },
    { w: "tarta", pos: "f.", zh: ["蛋糕，派"] },
    { w: "taxi", pos: "m.", zh: ["出租车"] },
    { w: "te", pos: "pron.", zh: ["你（宾格/与格代词）"] },
    { w: "teatro", pos: "m.", zh: ["剧院"] },
    { w: "teléfono", pos: "m.", zh: ["电话"] },
    { w: "tema", pos: "m.", zh: ["主题，话题"] },
    { w: "temprano", pos: "adv.", zh: ["早"] },
    { w: "tener", pos: "v.", zh: ["有；感到（tener que + inf. 必须做…）"], conj: "tener" },
    { w: "terminar", pos: "v.", zh: ["结束，完成"] },
    { w: "texto", pos: "m.", zh: ["课文，文本"] },
    { w: "ti", pos: "pron.", zh: ["你（介词后使用，para ti 给你的）"] },
    { w: "tía", pos: "f.", zh: ["阿姨；姑姑"] },
    { w: "tiempo", pos: "m.", zh: ["时间；天气"] },
    { w: "tienda", pos: "f.", zh: ["商店"] },
    { w: "tocar", pos: "v.", zh: ["弹奏；触摸（tocar la guitarra 弹吉他）"] },
    { w: "todavía", pos: "adv.", zh: ["还，仍然"] },
    { w: "todo, toda", pos: "adj./pron.", zh: ["全部的；一切（todos los días 每天）"] },
    { w: "tomar", pos: "v.", zh: ["拿；喝，吃（tomar café 喝咖啡）"] },
    { w: "trabajar", pos: "v.", zh: ["工作"], conj: "trabajar" },
    { w: "trabajo", pos: "m.", zh: ["工作"] },
    { w: "traer", pos: "v.", zh: ["带来"] },
    { w: "tranquilo, tranquila", pos: "adj.", zh: ["安静的，平静的"] },
    { w: "treinta", pos: "num.", zh: ["三十"] },
    { w: "tren", pos: "m.", zh: ["火车"] },
    { w: "tres", pos: "num.", zh: ["三"] },
    { w: "trozo", pos: "m.", zh: ["块，片"] },
    { w: "tu, tus, tú", pos: "adj./pron.", zh: ["你的", "你（tú，重音不同）"] },
    { w: "tuyo, tuya", pos: "pron.", zh: ["你的（物主代词）"] },
    { w: "un, una", pos: "art.", zh: ["一个（不定冠词）"] },
    { w: "universidad", pos: "f.", zh: ["大学"] },
    { w: "uno, unos, unas", pos: "num./art.", zh: ["一；一些"] },
    { w: "usted, ustedes", pos: "pron.", zh: ["您 / 诸位（正式称呼）"] },
    { w: "vacaciones", pos: "f.pl.", zh: ["假期（常为复数）"] },
    { w: "vale", pos: "interj.", zh: ["好的，行（¿vale? 好吗？）"] },
    { w: "valer", pos: "v.", zh: ["值，价值（valer la pena 值得）"] },
    { w: "vaso", pos: "m.", zh: ["杯子，玻璃杯"] },
    { w: "veinte", pos: "num.", zh: ["二十"] },
    { w: "veinticinco", pos: "num.", zh: ["二十五"] },
    { w: "veintinueve", pos: "num.", zh: ["二十九"] },
    { w: "veintitrés", pos: "num.", zh: ["二十三"] },
    { w: "veintiuno", pos: "num.", zh: ["二十一"] },
    { w: "vender", pos: "v.", zh: ["卖"] },
    { w: "venir", pos: "v.", zh: ["来"], conj: "venir" },
    { w: "ventana", pos: "f.", zh: ["窗户"] },
    { w: "ver", pos: "v.", zh: ["看，看见"] },
    { w: "verano", pos: "m.", zh: ["夏天"] },
    { w: "verdad", pos: "f.", zh: ["事实，真话（¿verdad? 对吧？）"] },
    { w: "verdura", pos: "f.", zh: ["蔬菜（常作 verduras）"] },
    { w: "vestido", pos: "m.", zh: ["连衣裙"] },
    { w: "vez", pos: "f.", zh: ["次，回（otra vez 再一次）"] },
    { w: "viajar", pos: "v.", zh: ["旅行"] },
    { w: "viaje", pos: "m.", zh: ["旅行"] },
    { w: "vida", pos: "f.", zh: ["生活；生命"] },
    { w: "viento", pos: "m.", zh: ["风"] },
    { w: "viernes", pos: "m.", zh: ["星期五"] },
    { w: "visita", pos: "f.", zh: ["拜访；参观"] },
    { w: "visitar", pos: "v.", zh: ["参观，拜访"] },
    { w: "vivir", pos: "v.", zh: ["居住；生活"], conj: "vivir" },
    { w: "volver", pos: "v.", zh: ["回来，返回（volver a + inf. 再次做…）"] },
    { w: "ya", pos: "adv.", zh: ["已经；马上（ya no 不再）"] },
    { w: "yo", pos: "pron.", zh: ["我"] },
    { w: "zapato", pos: "m.", zh: ["鞋子"] },
];

// 变形 → 原形索引（normalize 键）。
// 20 个核心动词的变形由 index.html 从 VERBS_DATA 自动生成，这里补：
// 其他动词的变位、副动词（-ando/-iendo）、过去分词、带宾格代词的形式。
var DICT_FORMS_DATA = {
    // ---- 副动词（gerundio） ----
    "aprendiendo": "aprender", "caminando": "caminar", "cocinando": "cocinar",
    "esperando": "esperar", "estudiando": "estudiar", "haciendo": "hacer",
    "jugando": "jugar", "lloviendo": "llover", "preparando": "preparar",
    "siguiendo": "seguir", "trabajando": "trabajar", "viviendo": "vivir",
    // ---- 过去分词 ----
    "abierto": "abrir", "abierta": "abrir", "abiertas": "abrir",
    "cerrado": "cerrar", "cerrada": "cerrar", "cerradas": "cerrar",
    "dicho": "decir", "escrito": "escribir", "escrita": "escribir", "escritas": "escribir",
    "hecho": "hacer", "ocupado": "ocupar", "ocupada": "ocupar",
    "organizado": "organizar", "pasada": "pasar", "preocupado": "preocuparse",
    "preocupada": "preocuparse", "puesto": "poner", "terminado": "terminar",
    "terminada": "terminar", "visitadas": "visitar", "visto": "ver",
    // ---- 不规则/其他动词变位 ----
    "acoste": "acostarse", "acuestas": "acostarse", "acuesta": "acostarse",
    "acuestan": "acostarse", "alegro": "alegrarse", "acuerdo": "acordar", "agradezco": "agradecer",
    "ayudas": "ayudar", "ayuda": "ayudar", "ayudes": "ayudar", "ayudo": "ayudar",
    "ayudame": "ayudar", "ayudarme": "ayudar", "ayudarte": "ayudar",
    "bebe": "beber", "bebemos": "beber", "bebo": "beber",
    "camine": "caminar", "caminamos": "caminar",
    "celebramos": "celebrar", "celebran": "celebrar",
    "cierra": "cerrar", "comienza": "comenzar", "conoceros": "conocer",
    "conocerte": "conocer", "conoces": "conocer", "conoci": "conocer",
    "conocimos": "conocer", "conozco": "conocer", "contestaste": "contestar",
    "corro": "correr", "creo": "creer", "cuenta": "contar", "cuentan": "contar",
    "cuesta": "costar", "cumple": "cumplir", "cumplio": "cumplir",
    "debo": "deber", "decidio": "decidir", "desayunamos": "desayunar",
    "descanses": "descansar", "descanso": "descansar", "devuelvo": "devolver",
    "dice": "decir", "digas": "decir", "divertiste": "divertirse",
    "dormimos": "dormir", "duele": "doler", "empecemos": "empezar",
    "empieza": "empezar", "empiezan": "empezar", "empezo": "empezar",
    "encanta": "encantar", "ensenarme": "enseñar", "entiendo": "entender",
    "escribe": "escribir", "escribimos": "escribir", "escribio": "escribir",
    "escribo": "escribir", "escucho": "escuchar", "espera": "esperar",
    "espere": "esperar", "esperes": "esperar", "espero": "esperar",
    "estudia": "estudiar", "estudian": "estudiar", "estudiamos": "estudiar",
    "estudie": "estudiar", "estudies": "estudiar", "estudio": "estudiar",
    "estuviste": "estar", "explico": "explicar", "falta": "faltar",
    "fumo": "fumar", "guardes": "guardar", "gusta": "gustar", "gustan": "gustar",
    "guste": "gustar", "habla": "hablar", "hable": "hablar", "hablemos": "hablar",
    "hables": "hablar", "hablamos": "hablar", "hablan": "hablar", "hablas": "hablar",
    "hablo": "hablar", "hace": "hacer", "haces": "hacer", "haga": "hacer",
    "hago": "hacer", "hay": "haber", "hazlo": "hacer", "he": "haber", "hiciste": "hacer",
    "invitamos": "invitar", "invitarte": "invitar", "invito": "invitar",
    "juegan": "jugar", "jugue": "jugar", "lavo": "lavar", "lee": "leer",
    "leo": "leer", "levanto": "levantarse", "levantas": "levantarse",
    "levantarme": "levantarse", "llama": "llamar", "llamas": "llamar",
    "llame": "llamar", "llamo": "llamar", "llega": "llegar", "llegamos": "llegar",
    "llegan": "llegar", "llego": "llegar", "lleguemos": "llegar",
    "lleva": "llevar", "llevamos": "llevar", "llevas": "llevar", "llevo": "llevar",
    "llovio": "llover", "llueva": "llover", "llueve": "llover",
    "manda": "mandar", "mira": "mirar", "necesito": "necesitar", "nieva": "nevar",
    "oigo": "oír", "organizo": "organizar", "parece": "parecer",
    "pase": "pasar", "paseamos": "pasear", "pasen": "pasar",
    "pedimos": "pedir", "pide": "pedir", "perdimos": "perder",
    "practico": "practicar", "preparamos": "preparar", "preocupe": "preocuparse",
    "quedamos": "quedar", "quede": "quedar", "quedo": "quedar",
    "quisiera": "querer", "recibe": "recibir", "recibimos": "recibir",
    "recomienda": "recomendar", "recomiendo": "recomendar",
    "repitamelo": "repetir", "sabe": "saber", "sabes": "saber",
    "sale": "salir", "salgo": "salir", "salio": "salir", "pon": "poner",
    "sientese": "sentar", "sientes": "sentir", "siga": "seguir",
    "sigo": "seguir", "sigue": "seguir", "sirven": "servir",
    "sorprende": "sorprender", "termine": "terminar", "termino": "terminar",
    "toca": "tocar", "tome": "tomar", "tomo": "tomar", "trae": "traer",
    "traigo": "traer", "trabaja": "trabajar", "trabajamos": "trabajar",
    "trabajan": "trabajar", "trabaje": "trabajar", "trabajo": "trabajar",
    "vale": "valer", "ve": "ver", "veas": "ver", "veces": "vez", "estos": "este",
    "vende": "vender", "venden": "vender", "veo": "ver", "ves": "ver",
    "viajamos": "viajar", "viene": "venir", "vienen": "venir", "vienes": "venir",
    "vimos": "ver", "vinieron": "venir", "visite": "visitar",
    "visitamos": "visitar", "vive": "vivir", "viven": "vivir",
    "vivimos": "vivir", "vivio": "vivir", "volvemos": "volver",
    "volvimos": "volver", "vuelve": "volver", "vuelvo": "volver",
    "verme": "ver", "comemos": "comer", "comimos": "comer", "come": "comer",
    "comas": "comer", "comamos": "comer", "comieron": "comer", "comiste": "comer",
    "compre": "comprar", "compramos": "comprar", "compro": "comprar",
};

